---
env:
  node: true
  jest: true
  es6: true
extends: 
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  require-jsdoc:
    - error
    - require:
        ClassDeclaration: true
        FunctionDeclaration: true
        MethodDefinition: true
  valid-jsdoc:
    - error
    - matchDescription: ".+"
      requireParamDescription: true
      requireParamType: true
      requireReturnType: true
  indent: 0
  "@typescript-eslint/indent": 
    - error
    - 2
  sort-keys: error
  sort-imports: error
