name: checks
on:
  pull_request:
    branches:
      - development

jobs:
  all:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          token: ${{ github.token }}
      - uses: actions/setup-node@v1
      - run: yarn test
